/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as farmNftSol from "./ FarmNft.sol";
export type { farmNftSol };
import type * as assetTokenizationSol from "./Asset-Tokenization.sol";
export type { assetTokenizationSol };
